name: buildroot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Build Repo
      run: |
        python3 spinarak.py
        echo "<html><head> <meta http-equiv='refresh' content='5; URL= http://apps.fortheusers.org/3ds' /></head></html>" > ./public/index.html
        
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: output
        path: public

    - name: Deploy Repo
      uses: crazy-max/ghaction-github-pages@v1.4.0
      with:
        build_dir: public
        fqdn: 3ds.apps.fortheusers.org
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
